# Generated by Django 5.2.3 on 2025-07-20 00:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('libro', 'Libro'), ('titulo', 'Título'), ('capitulo', 'Capítulo'), ('seccion', 'Sección'), ('subseccion', 'Subsección'), ('parte', 'Parte'), ('division', 'División'), ('otro', 'Otra Estructura')], max_length=20)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=300)),
                ('nivel', models.PositiveSmallIntegerField(default=0)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subestructuras', to='legal_docs.estructura')),
            ],
            options={
                'verbose_name_plural': 'Estructuras',
                'ordering': ['normativa', 'nivel', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(1)])),
                ('contenido', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('notas', models.TextField(blank=True, help_text='Notas o comentarios sobre el artículo')),
                ('estructura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='legal_docs.estructura')),
            ],
            options={
                'verbose_name_plural': 'Artículos',
                'ordering': ['normativa', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Inciso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('numero', 'Número'), ('letra', 'Letra'), ('roman', 'Romano'), ('item', 'Ítem')], max_length=10)),
                ('identificador', models.CharField(max_length=10)),
                ('contenido', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incisos', to='legal_docs.articulo')),
            ],
            options={
                'verbose_name_plural': 'Incisos',
                'ordering': ['articulo', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Normativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(default='Ecuador', max_length=100)),
                ('tipo', models.CharField(choices=[('constitucion', 'Constitución'), ('ley', 'Ley'), ('codigo', 'Código'), ('reglamento', 'Reglamento'), ('decreto', 'Decreto'), ('acuerdo', 'Acuerdo'), ('resolucion', 'Resolución'), ('otro', 'Otro')], max_length=50)),
                ('nombre', models.CharField(max_length=300)),
                ('nombre_corto', models.CharField(blank=True, max_length=100)),
                ('codigo', models.CharField(blank=True, help_text='Código oficial de la normativa', max_length=50)),
                ('fecha_publicacion', models.DateField()),
                ('fecha_vigencia', models.DateField()),
                ('vigente', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
                ('url_oficial', models.URLField(blank=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Normativas',
                'ordering': ['tipo', 'nombre'],
                'indexes': [models.Index(fields=['tipo'], name='legal_docs__tipo_a1d19a_idx'), models.Index(fields=['codigo'], name='legal_docs__codigo_cedde1_idx'), models.Index(fields=['vigente'], name='legal_docs__vigente_4eef6e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Modificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reforma', 'Reforma'), ('derogacion', 'Derogación'), ('adicion', 'Adición'), ('sustitucion', 'Sustitución')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('articulo_referencia', models.CharField(blank=True, max_length=100)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificaciones', to='legal_docs.articulo')),
                ('normativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificaciones', to='legal_docs.normativa')),
                ('normativa_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modificaciones_realizadas', to='legal_docs.normativa')),
            ],
            options={
                'verbose_name_plural': 'Modificaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='estructura',
            name='normativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estructuras', to='legal_docs.normativa'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='normativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='legal_docs.normativa'),
        ),
        migrations.AlterUniqueTogether(
            name='articulo',
            unique_together={('normativa', 'numero')},
        ),
    ]
